### ISSUE TITLE
Nodes stop synchronizing

### ISSUE THREAD

**Issue by COLUD4** [ericlee42/metis-verifier-node-setup#22] opened 2022-11-03 11:25 UTC
Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: insufficient balance for transfer

**Comment by ericlee42** [comment] 2022-11-03 11:31
I can't reproduce it. 

please ensure that your setup is the same with ours instruction.

**Comment by ericlee42** [comment] 2022-11-08 14:56
I will close this issue, if you're still experiencing the issue, please feel free to open it again.

**Closed as completed by ericlee42** 2022-11-08 14:56 UTC
